.TH SUBREG2ABRAFLEXI 1 "February 2026" "subreg2abraflexi 1.1.2" "User Commands"
.SH NAME
subreg2abraflexi \- Import Subreg Pricelist into AbraFlexi
.SH SYNOPSIS
.B subreg2abraflexi
[\fB\-o\fR \fIoutput\fR]
[\fB\-e\fR \fIenvironment\fR]
[\fB\-\-output\fR=\fIfile\fR]
[\fB\-\-environment\fR=\fIfile\fR]
.SH DESCRIPTION
.B subreg2abraflexi
imports domain pricing information from Subreg registrar API into AbraFlexi accounting system. 
The tool synchronizes product catalogs and pricing between the two systems.
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write output JSON data to FILE instead of stdout
.TP
\fB\-e\fR, \fB\-\-environment\fR=\fIFILE\fR
Load environment variables from FILE (default: ../.env)
.SH ENVIRONMENT
The following environment variables are used:
.TP
.B ABRAFLEXI_URL
AbraFlexi server URI (e.g., https://demo.flexibee.eu:5434)
.TP
.B ABRAFLEXI_LOGIN
AbraFlexi username
.TP
.B ABRAFLEXI_PASSWORD
AbraFlexi password
.TP
.B ABRAFLEXI_COMPANY
AbraFlexi company code
.TP
.B SUBREG_URI
Subreg SOAP endpoint (default: https://soap.subreg.cz/soap)
.TP
.B SUBREG_LOCATION
Subreg command endpoint (default: https://soap.subreg.cz/cmd.php)
.TP
.B SUBREG_LOGIN
Subreg username
.TP
.B SUBREG_PASSWORD
Subreg password
.TP
.B APP_DEBUG
Enable debug output (true/false)
.TP
.B RESULT_FILE
Default output file for results
.SH EXIT STATUS
.TP
0
Success
.TP
1
General error
.SH FILES
.TP
.I ../.env
Default environment file
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
.SH SEE ALSO
.BR subreg2abraflexi-init (1),
.BR subreg-check-credit (1)